spring:
  jpa:
    show-sql: true

  liquibase:
    contexts: dev

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: ${mailtrap.user}
    password: ${mailtrap.password}
    properties:
      mail.debug: true