version: "3.7"

services:
  postgres:
    container_name: wb-database
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=webbudget
      - POSTGRES_USER=sa_webbudget
      - POSTGRES_PASSWORD=sa_webbudget
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    networks:
      wb_network:
        aliases:
          - postgres
  redis:
    image: redis:6-alpine
    container_name: wb-cache
    ports:
      - 6379:6379
    networks:
      wb_network:
        aliases:
          - redis

networks:
  wb_network:
    driver: bridge