version: "3.7"

services:
  postgres:
    container_name: wb-database
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=webbudget
      - POSTGRES_USER=sa_webbudget
      - POSTGRES_PASSWORD=sa_webbudget
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:6-alpine
    container_name: wb-cache
    ports:
      - "6380:6379"
    volumes:
      - data-redis:/data
    networks:
      - default

volumes:
  data-postgres:
    driver: local
  data-redis:
    driver: local

networks:
  default:
    driver: bridge