name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate gradle
        uses: gradle/wrapper-validation-action@v1
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: detekt --no-daemon
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test --no-daemon
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build --no-daemon --scan -x test detekt