name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: validate gradle
        uses: gradle/wrapper-validation-action@v1
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test --no-daemon
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build --no-daemon --scan -x test